// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/job/v1beta1/job.proto

package v1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobServiceClient interface {
	ImportJob(ctx context.Context, in *ImportJobRequest, opts ...grpc.CallOption) (*ImportJobResponse, error)
	ExportJob(ctx context.Context, in *ExportJobRequest, opts ...grpc.CallOption) (*ExportJobResponse, error)
	GetAvailableJobs(ctx context.Context, in *GetAvailableJobsRequest, opts ...grpc.CallOption) (*GetAvailableJobsResponse, error)
}

type jobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobServiceClient(cc grpc.ClientConnInterface) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) ImportJob(ctx context.Context, in *ImportJobRequest, opts ...grpc.CallOption) (*ImportJobResponse, error) {
	out := new(ImportJobResponse)
	err := c.cc.Invoke(ctx, "/api.job.v1beta1.JobService/ImportJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ExportJob(ctx context.Context, in *ExportJobRequest, opts ...grpc.CallOption) (*ExportJobResponse, error) {
	out := new(ExportJobResponse)
	err := c.cc.Invoke(ctx, "/api.job.v1beta1.JobService/ExportJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetAvailableJobs(ctx context.Context, in *GetAvailableJobsRequest, opts ...grpc.CallOption) (*GetAvailableJobsResponse, error) {
	out := new(GetAvailableJobsResponse)
	err := c.cc.Invoke(ctx, "/api.job.v1beta1.JobService/GetAvailableJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
// All implementations should embed UnimplementedJobServiceServer
// for forward compatibility
type JobServiceServer interface {
	ImportJob(context.Context, *ImportJobRequest) (*ImportJobResponse, error)
	ExportJob(context.Context, *ExportJobRequest) (*ExportJobResponse, error)
	GetAvailableJobs(context.Context, *GetAvailableJobsRequest) (*GetAvailableJobsResponse, error)
}

// UnimplementedJobServiceServer should be embedded to have forward compatible implementations.
type UnimplementedJobServiceServer struct {
}

func (UnimplementedJobServiceServer) ImportJob(context.Context, *ImportJobRequest) (*ImportJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportJob not implemented")
}
func (UnimplementedJobServiceServer) ExportJob(context.Context, *ExportJobRequest) (*ExportJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportJob not implemented")
}
func (UnimplementedJobServiceServer) GetAvailableJobs(context.Context, *GetAvailableJobsRequest) (*GetAvailableJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableJobs not implemented")
}

// UnsafeJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobServiceServer will
// result in compilation errors.
type UnsafeJobServiceServer interface {
	mustEmbedUnimplementedJobServiceServer()
}

func RegisterJobServiceServer(s grpc.ServiceRegistrar, srv JobServiceServer) {
	s.RegisterService(&JobService_ServiceDesc, srv)
}

func _JobService_ImportJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ImportJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.job.v1beta1.JobService/ImportJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ImportJob(ctx, req.(*ImportJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ExportJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ExportJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.job.v1beta1.JobService/ExportJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ExportJob(ctx, req.(*ExportJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetAvailableJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetAvailableJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.job.v1beta1.JobService/GetAvailableJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetAvailableJobs(ctx, req.(*GetAvailableJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobService_ServiceDesc is the grpc.ServiceDesc for JobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.job.v1beta1.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImportJob",
			Handler:    _JobService_ImportJob_Handler,
		},
		{
			MethodName: "ExportJob",
			Handler:    _JobService_ExportJob_Handler,
		},
		{
			MethodName: "GetAvailableJobs",
			Handler:    _JobService_GetAvailableJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/job/v1beta1/job.proto",
}
