// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/job/v1beta1/jobstate.proto

package v1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on JobStateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *JobStateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JobStateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// JobStateRequestMultiError, or nil if none found.
func (m *JobStateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *JobStateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for JobId

	// no validation rules for State

	if len(errors) > 0 {
		return JobStateRequestMultiError(errors)
	}

	return nil
}

// JobStateRequestMultiError is an error wrapping multiple validation errors
// returned by JobStateRequest.ValidateAll() if the designated constraints
// aren't met.
type JobStateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JobStateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JobStateRequestMultiError) AllErrors() []error { return m }

// JobStateRequestValidationError is the validation error returned by
// JobStateRequest.Validate if the designated constraints aren't met.
type JobStateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JobStateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JobStateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JobStateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JobStateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JobStateRequestValidationError) ErrorName() string { return "JobStateRequestValidationError" }

// Error satisfies the builtin error interface
func (e JobStateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJobStateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JobStateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JobStateRequestValidationError{}

// Validate checks the field values on JobStateResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *JobStateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JobStateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// JobStateResponseMultiError, or nil if none found.
func (m *JobStateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *JobStateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for JobId

	// no validation rules for State

	if len(errors) > 0 {
		return JobStateResponseMultiError(errors)
	}

	return nil
}

// JobStateResponseMultiError is an error wrapping multiple validation errors
// returned by JobStateResponse.ValidateAll() if the designated constraints
// aren't met.
type JobStateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JobStateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JobStateResponseMultiError) AllErrors() []error { return m }

// JobStateResponseValidationError is the validation error returned by
// JobStateResponse.Validate if the designated constraints aren't met.
type JobStateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JobStateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JobStateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JobStateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JobStateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JobStateResponseValidationError) ErrorName() string { return "JobStateResponseValidationError" }

// Error satisfies the builtin error interface
func (e JobStateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJobStateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JobStateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JobStateResponseValidationError{}
