// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/job/v1beta1/jobstate.proto

package v1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JobStateServiceClient is the client API for JobStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobStateServiceClient interface {
	GetJobState(ctx context.Context, in *GetJobStateRequest, opts ...grpc.CallOption) (*GetJobStateResponse, error)
	UpdateJobState(ctx context.Context, in *UpdateJobStateRequest, opts ...grpc.CallOption) (*UpdateJobStateResponse, error)
}

type jobStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobStateServiceClient(cc grpc.ClientConnInterface) JobStateServiceClient {
	return &jobStateServiceClient{cc}
}

func (c *jobStateServiceClient) GetJobState(ctx context.Context, in *GetJobStateRequest, opts ...grpc.CallOption) (*GetJobStateResponse, error) {
	out := new(GetJobStateResponse)
	err := c.cc.Invoke(ctx, "/api.job.v1beta1.JobStateService/GetJobState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobStateServiceClient) UpdateJobState(ctx context.Context, in *UpdateJobStateRequest, opts ...grpc.CallOption) (*UpdateJobStateResponse, error) {
	out := new(UpdateJobStateResponse)
	err := c.cc.Invoke(ctx, "/api.job.v1beta1.JobStateService/UpdateJobState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobStateServiceServer is the server API for JobStateService service.
// All implementations should embed UnimplementedJobStateServiceServer
// for forward compatibility
type JobStateServiceServer interface {
	GetJobState(context.Context, *GetJobStateRequest) (*GetJobStateResponse, error)
	UpdateJobState(context.Context, *UpdateJobStateRequest) (*UpdateJobStateResponse, error)
}

// UnimplementedJobStateServiceServer should be embedded to have forward compatible implementations.
type UnimplementedJobStateServiceServer struct {
}

func (UnimplementedJobStateServiceServer) GetJobState(context.Context, *GetJobStateRequest) (*GetJobStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobState not implemented")
}
func (UnimplementedJobStateServiceServer) UpdateJobState(context.Context, *UpdateJobStateRequest) (*UpdateJobStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobState not implemented")
}

// UnsafeJobStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobStateServiceServer will
// result in compilation errors.
type UnsafeJobStateServiceServer interface {
	mustEmbedUnimplementedJobStateServiceServer()
}

func RegisterJobStateServiceServer(s grpc.ServiceRegistrar, srv JobStateServiceServer) {
	s.RegisterService(&JobStateService_ServiceDesc, srv)
}

func _JobStateService_GetJobState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobStateServiceServer).GetJobState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.job.v1beta1.JobStateService/GetJobState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobStateServiceServer).GetJobState(ctx, req.(*GetJobStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobStateService_UpdateJobState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobStateServiceServer).UpdateJobState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.job.v1beta1.JobStateService/UpdateJobState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobStateServiceServer).UpdateJobState(ctx, req.(*UpdateJobStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobStateService_ServiceDesc is the grpc.ServiceDesc for JobStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.job.v1beta1.JobStateService",
	HandlerType: (*JobStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJobState",
			Handler:    _JobStateService_GetJobState_Handler,
		},
		{
			MethodName: "UpdateJobState",
			Handler:    _JobStateService_UpdateJobState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/job/v1beta1/jobstate.proto",
}
