// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/status/v1beta1/uptime.proto

package v1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UptimeServiceClient is the client API for UptimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UptimeServiceClient interface {
	GetUptime(ctx context.Context, in *GetUptimeRequest, opts ...grpc.CallOption) (*GetUptimeResponse, error)
}

type uptimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUptimeServiceClient(cc grpc.ClientConnInterface) UptimeServiceClient {
	return &uptimeServiceClient{cc}
}

func (c *uptimeServiceClient) GetUptime(ctx context.Context, in *GetUptimeRequest, opts ...grpc.CallOption) (*GetUptimeResponse, error) {
	out := new(GetUptimeResponse)
	err := c.cc.Invoke(ctx, "/api.status.v1beta1.UptimeService/GetUptime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UptimeServiceServer is the server API for UptimeService service.
// All implementations should embed UnimplementedUptimeServiceServer
// for forward compatibility
type UptimeServiceServer interface {
	GetUptime(context.Context, *GetUptimeRequest) (*GetUptimeResponse, error)
}

// UnimplementedUptimeServiceServer should be embedded to have forward compatible implementations.
type UnimplementedUptimeServiceServer struct {
}

func (UnimplementedUptimeServiceServer) GetUptime(context.Context, *GetUptimeRequest) (*GetUptimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUptime not implemented")
}

// UnsafeUptimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UptimeServiceServer will
// result in compilation errors.
type UnsafeUptimeServiceServer interface {
	mustEmbedUnimplementedUptimeServiceServer()
}

func RegisterUptimeServiceServer(s grpc.ServiceRegistrar, srv UptimeServiceServer) {
	s.RegisterService(&UptimeService_ServiceDesc, srv)
}

func _UptimeService_GetUptime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUptimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UptimeServiceServer).GetUptime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.status.v1beta1.UptimeService/GetUptime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UptimeServiceServer).GetUptime(ctx, req.(*GetUptimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UptimeService_ServiceDesc is the grpc.ServiceDesc for UptimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UptimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.status.v1beta1.UptimeService",
	HandlerType: (*UptimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUptime",
			Handler:    _UptimeService_GetUptime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/status/v1beta1/uptime.proto",
}
