// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/location/v1beta1/detect.proto

package v1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DetectCrossingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DetectCrossingsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DetectCrossingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DetectCrossingsRequestMultiError, or nil if none found.
func (m *DetectCrossingsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DetectCrossingsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AreaKey

	for idx, item := range m.GetValues() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DetectCrossingsRequestValidationError{
						field:  fmt.Sprintf("Values[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DetectCrossingsRequestValidationError{
						field:  fmt.Sprintf("Values[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DetectCrossingsRequestValidationError{
					field:  fmt.Sprintf("Values[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for ValidateOnly

	if len(errors) > 0 {
		return DetectCrossingsRequestMultiError(errors)
	}

	return nil
}

// DetectCrossingsRequestMultiError is an error wrapping multiple validation
// errors returned by DetectCrossingsRequest.ValidateAll() if the designated
// constraints aren't met.
type DetectCrossingsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DetectCrossingsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DetectCrossingsRequestMultiError) AllErrors() []error { return m }

// DetectCrossingsRequestValidationError is the validation error returned by
// DetectCrossingsRequest.Validate if the designated constraints aren't met.
type DetectCrossingsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DetectCrossingsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DetectCrossingsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DetectCrossingsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DetectCrossingsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DetectCrossingsRequestValidationError) ErrorName() string {
	return "DetectCrossingsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DetectCrossingsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDetectCrossingsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DetectCrossingsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DetectCrossingsRequestValidationError{}

// Validate checks the field values on DetectCrossingsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DetectCrossingsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DetectCrossingsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DetectCrossingsResponseMultiError, or nil if none found.
func (m *DetectCrossingsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DetectCrossingsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AreaKey

	for idx, item := range m.GetValues() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DetectCrossingsResponseValidationError{
						field:  fmt.Sprintf("Values[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DetectCrossingsResponseValidationError{
						field:  fmt.Sprintf("Values[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DetectCrossingsResponseValidationError{
					field:  fmt.Sprintf("Values[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DetectCrossingsResponseMultiError(errors)
	}

	return nil
}

// DetectCrossingsResponseMultiError is an error wrapping multiple validation
// errors returned by DetectCrossingsResponse.ValidateAll() if the designated
// constraints aren't met.
type DetectCrossingsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DetectCrossingsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DetectCrossingsResponseMultiError) AllErrors() []error { return m }

// DetectCrossingsResponseValidationError is the validation error returned by
// DetectCrossingsResponse.Validate if the designated constraints aren't met.
type DetectCrossingsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DetectCrossingsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DetectCrossingsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DetectCrossingsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DetectCrossingsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DetectCrossingsResponseValidationError) ErrorName() string {
	return "DetectCrossingsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DetectCrossingsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDetectCrossingsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DetectCrossingsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DetectCrossingsResponseValidationError{}
