// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/location/v1beta1/location_update.proto

package v1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LocationUpdate with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LocationUpdate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LocationUpdate with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LocationUpdateMultiError,
// or nil if none found.
func (m *LocationUpdate) ValidateAll() error {
	return m.validate(true)
}

func (m *LocationUpdate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetWorkerId() != "" {

		if utf8.RuneCountInString(m.GetWorkerId()) > 20 {
			err := LocationUpdateValidationError{
				field:  "WorkerId",
				reason: "value length must be at most 20 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if all {
		switch v := interface{}(m.GetLocation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LocationUpdateValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LocationUpdateValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLocation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LocationUpdateValidationError{
				field:  "Location",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetUpdateTime() == nil {
		err := LocationUpdateValidationError{
			field:  "UpdateTime",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LocationUpdateMultiError(errors)
	}

	return nil
}

// LocationUpdateMultiError is an error wrapping multiple validation errors
// returned by LocationUpdate.ValidateAll() if the designated constraints
// aren't met.
type LocationUpdateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LocationUpdateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LocationUpdateMultiError) AllErrors() []error { return m }

// LocationUpdateValidationError is the validation error returned by
// LocationUpdate.Validate if the designated constraints aren't met.
type LocationUpdateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LocationUpdateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LocationUpdateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LocationUpdateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LocationUpdateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LocationUpdateValidationError) ErrorName() string { return "LocationUpdateValidationError" }

// Error satisfies the builtin error interface
func (e LocationUpdateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLocationUpdate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LocationUpdateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LocationUpdateValidationError{}
